[platformio]
default_envs = release

[env]
lib_compat_mode = strict
platform = https://github.com/pioarduino/platform-espressif32.git
framework = arduino
board = esp32-c3-devkitc-02
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DELEGANTOTA_USE_ASYNC_WEBSERVER=1
    !echo "-D BUILD_TIME='\"$(date --rfc-3339=seconds)\"'"
    !echo "-D GIT_TAG='\"$(git describe --tags --always)\"'"
    !echo "-D GIT_COMMIT='\"$(git log -1 --format=%%h)\"'"
lib_deps =
    adafruit/Adafruit_VL53L0X
    adafruit/Adafruit SSD1306
    adafruit/Adafruit NeoPixel
    https://github.com/s00500/ESPUI.git#c7b7edf7c9475b01ece240b6195f3a9f21f43935
    ayushsharma82/ElegantOTA

[env:release]

[env:debug]
build_type = debug
build_flags =
    ${env.build_flags}
    -DDEBUG
    ; -DDEBUG_ESPUI

[env:ota]
upload_protocol = espota
upload_port = vodka.local
upload_flags = --auth=12345678
